# Generated by Django 5.1.6 on 2026-05-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_data_migrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="Blood_Group",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Blood Group"
            ),
        ),
    ]
