# Generated by Django 5.1.6 on 2026-06-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_driver_blood_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={},
        ),
    ]
