# Generated by Django 5.1.6 on 2026-06-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_drop_driver_age_column"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="age",
        ),
    ]
