# Generated by Django 5.1.6 on 2026-06-25 18:12

import django.db.models.deletion
from django.db import migrations, models



def migrate_training_data(apps, schema_editor):
    annual_training_driver = apps.get_model("dashboard", "annual_training_driver")
    annual_drill_driver = apps.get_model("dashboard", "annual_drill_driver")
    DriverTrainingCompletion = apps.get_model("dashboard", "DriverTrainingCompletion")
    DriverDrillCompletion = apps.get_model("dashboard", "DriverDrillCompletion")
    annual_training = apps.get_model("dashboard", "annual_training")
    annual_drill = apps.get_model("dashboard", "annual_drill")

    for row in annual_training_driver.objects.all():
        for slot in range(1, 13):
            field_name = f"train{slot}_completed_date"
            date_val = getattr(row, field_name, None)
            if date_val is None:
                continue
            try:
                training = annual_training.objects.get(pk=slot)
            except annual_training.DoesNotExist:
                continue
            DriverTrainingCompletion.objects.get_or_create(
                driver=row.user,
                training=training,
                defaults={"completed_date": date_val},
            )

    for row in annual_drill_driver.objects.all():
        for slot in range(1, 13):
            field_name = f"train{slot}_completed_date"
            date_val = getattr(row, field_name, None)
            if date_val is None:
                continue
            try:
                drill = annual_drill.objects.get(pk=slot)
            except annual_drill.DoesNotExist:
                continue
            DriverDrillCompletion.objects.get_or_create(
                driver=row.user,
                drill=drill,
                defaults={"completed_date": date_val},
            )


# ── Migration class ───────────────────────────────────────────────────────────

class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_drop_driver_age_column"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annual_drill_driver",
            options={
                "verbose_name": "Drill Driver",
                "verbose_name_plural": "Drill Drivers",
            },
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name_plural": "Drivers"},
        ),
        migrations.CreateModel(
            name="DriverDrillCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_date", models.DateField()),
                (
                    "drill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_completions",
                        to="dashboard.annual_drill",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drill_completions",
                        to="dashboard.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Drill Completion",
                "verbose_name_plural": "Driver Drill Completions",
                "unique_together": {("driver", "drill")},
            },
        ),
        migrations.CreateModel(
            name="DriverTrainingCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_date", models.DateField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_completions",
                        to="dashboard.driver",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_completions",
                        to="dashboard.annual_training",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Training Completion",
                "verbose_name_plural": "Driver Training Completions",
                "unique_together": {("driver", "training")},
            },
        ),
        migrations.RunPython(migrate_training_data, migrations.RunPython.noop),
    ]