# Generated by Django 5.1.6 on 2026-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_add_soft_delete_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dm", "Driver Management"),
                            ("vm", "Vehicle Management"),
                            ("hse", "HSE"),
                            ("op", "Operation Procedure"),
                        ],
                        max_length=10,
                    ),
                ),
                ("body", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "id"],
            },
        ),
    ]
