# Generated by Django 5.1.6 on 2026-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_procedure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="category",
            field=models.CharField(
                choices=[
                    ("dm", "Driver Management"),
                    ("vm", "Vehicle Management"),
                    ("hse", "HSE"),
                    ("op", "Operation Procedure"),
                    ("general", "General"),
                ],
                max_length=10,
            ),
        ),
    ]
