# Generated by Django 5.1.6 on 2026-08-07 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_update_catalogue_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="driver",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("CNIC",),
                name="uniq_driver_cnic_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("TL_Number",),
                name="uniq_vehicle_tlnumber_active",
            ),
        ),
    ]
